services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example


  shopping-api:
    image: israelsz13/shopping-api:1.0
    ports:
      - 4000:4000

    environment:
      - MONGODB_HOST=mongo
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=example

      